### ISSUE TITLE
Problems about extract_3D_feat.py

### ISSUE THREAD

**Issue by XinyuLyu** [YapengTian/AVVP-ECCV20#2]
Hi Yapeng, 
When I try to use extract_3D_feat.py to extract 3D feature from image frames, it has such error. Could you please help me figure it out? By the way, the torch version is 1.2.0. Many thanks!
![image](https://user-images.githubusercontent.com/33551398/94367440-6fff3480-0111-11eb-89b6-089fcfd7c1c2.png)

**Comment by YapengTian** [comment]
Sorry for the late response. It seems that it calls the utils in the pretrainedmodels library but actually it should use the utils in the scripts folder.

**Comment by XinyuLyu** [comment]
Thank you so much!
