### ISSUE TITLE
what does the "second-wise temporal boundaries" mean when you mention the indivual audio and visual events in your datasets?

### ISSUE THREAD

**Issue by a-flying-crow** [YapengTian/AVVP-ECCV20#3]
Does it means its tenporal boundaries might be shorter than the a-v boundary?

**Comment by YapengTian** [comment]
Sorry for the late response! I did not receive an email to remind me the issue. 

It just means that individual audio event and visual event temporal boundaries. Here, the second-wise temporal boundary annotation is corresponding to first-wise video-level labels.
