### ISSUE TITLE
Does the raw data set have a cloud link

### ISSUE THREAD

**Issue by a-flying-crow** [YapengTian/AVVP-ECCV20#4]
Hi，I wanna use your data to do some experiments, but there seems to be something wrong with the download. Is there any cloud link of your raw data of Video? Thanks a lot.

**Comment by YapengTian** [comment]
What is the download issue? Unfortunately, we have not uploaded it to cloud. Due to copyright issues, we might not be able to do this.

**Comment by a-flying-crow** [comment]
"ERROR: Unable to download webpage: <urlopen error EOF occurred in violation of protocol (_ssl.c:852)> (caused by URLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:852)'),))" It seems to be some network problems.

**Comment by a-flying-crow** [comment]
It's wired that some video that I can download successfully while there are still some videos which could not

**Comment by YapengTian** [comment]
It is really weird. It seems that the issue is from your network.  If you are not working on feature learning,  you might use the extracted features directly, which have already shared in the repo.

**Comment by wcq19941215** [comment]
It seems that the original video has been deleted 
![image](https://user-images.githubusercontent.com/35086262/102733902-72bc9f00-4379-11eb-9634-b3d33bc92dc9.png)

**Comment by YapengTian** [comment]
Yes, some Youtube videos might be deleted. But, most of the videos should be available.

**Comment by a-flying-crow** [comment]
Thanks for your answering. Does the features you have extracted  which is up to the Google Drive contain all the data in your dataset?

**Comment by YapengTian** [comment]
Yeah. The features should be able to reproduce our results.
