### ISSUE TITLE
Hi,what does "pretrainedmodels library" mean which you mentioned around the video extractor 

### ISSUE THREAD

**Issue by a-flying-crow** [YapengTian/AVVP-ECCV20#5]
and I wanna to know what is these pretrained models' pretrain task or dataset

**Comment by YapengTian** [comment]
Here is the library: https://github.com/Cadene/pretrained-models.pytorch.

**Comment by a-flying-crow** [comment]
> Here is the library: https://github.com/Cadene/pretrained-models.pytorch. The pretrained models were trained on Imagenet. 

Thanks for your response
