### ISSUE TITLE
I wanna to reproduce your experiments compared with other methods

### ISSUE THREAD

**Issue by a-flying-crow** [YapengTian/AVVP-ECCV20#6]
could you give me some guidance about your way to extract features that other methods used such as I3D and UNT

**Comment by a-flying-crow** [comment]
such as the way you to get the optical flow

**Comment by YapengTian** [comment]
Sorry for the late response. 

As described in the Readme, I provided the used scripts for feature extraction. If you want to extract other features, I think it should be easy by modifying the provided scripts.
